# Use
#    @warnpcfail precompile(args...)
# if you want to be warned when a precompile directive fails
macro warnpcfail(ex::Expr)
    modl = __module__
    file = __source__.file === nothing ? "?" : String(__source__.file)
    line = __source__.line
    quote
        $(esc(ex)) || @warn """precompile directive
     $($(Expr(:quote, ex)))
 failed. Please report an issue in $($modl) (after checking for duplicates) or remove this directive.""" _file=$file _line=$line
    end
end


function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    @warnpcfail Base.precompile(Tuple{Type{replace_inds},Pair{OpIndex, OpIndex},Vararg{Pair{OpIndex, OpIndex}, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(*),Complex{Int},OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(*),Complex{Rational{Int}},OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(*),OpSum,Int})
    @warnpcfail Base.precompile(Tuple{typeof(*),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(+),Int,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(+),OpSum,Complex{Rational{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(+),OpSum,Float64})
    @warnpcfail Base.precompile(Tuple{typeof(+),OpSum,Int})
    @warnpcfail Base.precompile(Tuple{typeof(+),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(+),Rational{Int},OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(-),Int,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(-),OpSum,Int})
    @warnpcfail Base.precompile(Tuple{typeof(==),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(Avac),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(CorrTup_isless),NTuple{4, Int},Tuple{Int, Int}})
    @warnpcfail Base.precompile(Tuple{typeof(CorrTup_isless),NTuple{6, Int},Tuple{Int, Int, Int}})
    @warnpcfail Base.precompile(Tuple{typeof(CorrTup_isless),NTuple{8, Int},NTuple{4, Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_corrs!),OpSum,OpTerm,Int,typeof(_add_with_normal_order!)})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,ComplexF64,ComplexF64})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,ComplexF64,Float64})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Int},Complex{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Int},Int})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Int},Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Complex{Rational{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Int})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Float64,Float64})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Int,Int})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Int,Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Rational{Int},Int})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Rational{Int},Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(_add_sum_term!),OpSum,OpTerm,Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(adjoint),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(boson_ops),Symbol})
    @warnpcfail Base.precompile(Tuple{typeof(comm),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(corr),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(expval_as_corrs),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(fermion_ops),Symbol})
    @warnpcfail Base.precompile(Tuple{typeof(isapprox),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(isempty),OpTerm})
    @warnpcfail Base.precompile(Tuple{typeof(julia_expression),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(julia_expression),Param,Nothing})
    @warnpcfail Base.precompile(Tuple{typeof(latex),Complex{Rational{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(latex),Float64})
    @warnpcfail Base.precompile(Tuple{typeof(latex),Int})
    @warnpcfail Base.precompile(Tuple{typeof(latex),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(latex),OpTerm})
    @warnpcfail Base.precompile(Tuple{typeof(latex),Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Int,Int,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Int,Symbol,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Int,Symbol})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Symbol,Int,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Symbol,Int})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Symbol,String})
    @warnpcfail Base.precompile(Tuple{typeof(make_indices),Symbol,Symbol,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(normal_form),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Int,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Int})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Symbol,Vararg{Any, N} where N})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Tuple{}})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Vector{Any}})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Vector{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char,Vector{Symbol}})
    @warnpcfail Base.precompile(Tuple{typeof(param),Symbol,Char})
    @warnpcfail Base.precompile(Tuple{typeof(parse_paramstr),String})
    @warnpcfail Base.precompile(Tuple{typeof(print),IOBuffer,BaseOperator})
    @warnpcfail Base.precompile(Tuple{typeof(print),IOBuffer,Corr})
    @warnpcfail Base.precompile(Tuple{typeof(print_term_scalar),IOBuffer,OpTerm,Complex{Int},Bool})
    @warnpcfail Base.precompile(Tuple{typeof(print_term_scalar),IOBuffer,OpTerm,Int,Bool})
    @warnpcfail Base.precompile(Tuple{typeof(print_term_scalar),IOBuffer,OpTerm,Rational{Int},Bool})
    @warnpcfail Base.precompile(Tuple{typeof(show),IOBuffer,MIME{Symbol("text/latex")},OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(simplify_number),Rational{Int}})
    @warnpcfail Base.precompile(Tuple{typeof(symmetric_index_nums),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{4, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{4, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{5, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{6, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{7, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{8, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,NTuple{9, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{4, Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{5, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{6, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{7, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{8, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{NTuple{9, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int, Int}, Tuple{Int, Int, Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int, Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{4, Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{5, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{6, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{7, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, NTuple{8, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int, Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, NTuple{5, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, NTuple{6, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, NTuple{7, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{5, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{6, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{5, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, NTuple{4, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int}, Tuple{Int, Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}, Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(term2corr),OpTerm,Tuple{Tuple{Int}}})
    @warnpcfail Base.precompile(Tuple{typeof(use_σpm),Bool})
    @warnpcfail Base.precompile(Tuple{typeof(vacA),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(vacExpVal),OpSum,OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(vacExpVal),OpSum})
    @warnpcfail Base.precompile(Tuple{typeof(∑),Symbol,OpSum})
end
