function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{Core.kwftype(typeof(Base.Sort.sort!)),NamedTuple{(:lt,),Tuple{typeof(QuantumAlgebra.CorrTup_isless)}},typeof(sort!),Array{NTuple{4,Int},1}})
    Base.precompile(Tuple{Core.kwftype(typeof(Base.Sort.sort!)),NamedTuple{(:lt,),Tuple{typeof(QuantumAlgebra.CorrTup_isless)}},typeof(sort!),Array{Tuple{Int,Int,Int},1}})
    Base.precompile(Tuple{Core.kwftype(typeof(Base.Sort.sort!)),NamedTuple{(:lt,),Tuple{typeof(QuantumAlgebra.CorrTup_isless)}},typeof(sort!),Array{Tuple{Int,Int},1}})
    Base.precompile(Tuple{Core.kwftype(typeof(Base.Sort.sort!)),NamedTuple{(:lt,),Tuple{typeof(QuantumAlgebra.CorrTup_isless)}},typeof(sort!),Array{Tuple{Int,Vararg{Int,N} where N},1}})
    Base.precompile(Tuple{Type{Array{Tuple{OpTerm,Number},1}},UndefInitializer,Int})
    Base.precompile(Tuple{Type{Array{Tuple{OpTerm,Real},1}},UndefInitializer,Int})
    Base.precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Axes,F,Args} where Args<:Tuple where F where Axes},typeof(corr),Tuple{Array{OpSum,1}}})
    Base.precompile(Tuple{Type{Base.Generator},Type{OpIndex},Tuple{Int,Int,Symbol}})
    Base.precompile(Tuple{Type{Base.Generator},Type{OpIndex},Tuple{Symbol,Symbol,Int}})
    Base.precompile(Tuple{Type{Base.Generator},Type{OpIndex},Tuple{Symbol,Symbol,Symbol}})
    Base.precompile(Tuple{Type{Dict{OpIndex,OpIndex}},Pair{OpIndex,OpIndex},Vararg{Pair{OpIndex,OpIndex},N} where N})
    Base.precompile(Tuple{Type{Dict{OpIndex,OpIndex}}})
    Base.precompile(Tuple{Type{Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}}}})
    Base.precompile(Tuple{typeof(!=),OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),Float64,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),Int,OpSum,OpSum,OpSum,OpSum,OpSum,Vararg{OpSum,N} where N})
    Base.precompile(Tuple{typeof(*),Int,OpSum,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),Int,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),Int,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),OpSum,Int})
    Base.precompile(Tuple{typeof(*),OpSum,OpSum,OpSum,OpSum,OpSum,OpSum,Vararg{OpSum,N} where N})
    Base.precompile(Tuple{typeof(*),OpSum,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(*),Rational{Int},OpSum,OpSum})
    Base.precompile(Tuple{typeof(+),OpSum,OpSum,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(+),OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(+),Rational{Int},OpSum})
    Base.precompile(Tuple{typeof(==),Array{BaseOperator,1},Array{BaseOperator,1}})
    Base.precompile(Tuple{typeof(==),Array{OpIndex,1},Array{OpIndex,1}})
    Base.precompile(Tuple{typeof(==),Array{Param,1},Array{Param,1}})
    Base.precompile(Tuple{typeof(==),Array{QuantumAlgebra.Corr,1},Array{QuantumAlgebra.Corr,1}})
    Base.precompile(Tuple{typeof(==),Array{QuantumAlgebra.ExpVal,1},Array{QuantumAlgebra.ExpVal,1}})
    Base.precompile(Tuple{typeof(==),Array{δ,1},Array{δ,1}})
    Base.precompile(Tuple{typeof(==),Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}}})
    Base.precompile(Tuple{typeof(Avac),OpSum})
    Base.precompile(Tuple{typeof(Base.Broadcast._broadcast_getindex_evalf),typeof(QuantumAlgebra.indices),Array{Param,1}})
    Base.precompile(Tuple{typeof(Base.Broadcast._broadcast_getindex_evalf),typeof(QuantumAlgebra.indices),Array{QuantumAlgebra.Corr,1}})
    Base.precompile(Tuple{typeof(Base.Broadcast._broadcast_getindex_evalf),typeof(QuantumAlgebra.indices),Array{QuantumAlgebra.ExpVal,1}})
    Base.precompile(Tuple{typeof(Base.Broadcast._broadcast_getindex_evalf),typeof(QuantumAlgebra.indices),Array{δ,1}})
    Base.precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,Array{OpSum,1}})
    Base.precompile(Tuple{typeof(Base.Broadcast.broadcasted),QuantumAlgebra.reorder_suminds,Base.Iterators.Flatten{Tuple{Array{δ,1},Array{δ,1}}}})
    Base.precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Array{Any,1},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},typeof(QuantumAlgebra.indices),Tuple{Base.Broadcast.Extruded{Array{OpTerm,1},Tuple{Bool},Tuple{Int}}}},Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Tuple{OpTerm,Float64},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Tuple{OpTerm,Int},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Tuple{OpTerm,Rational{Int}},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,QuantumAlgebra.reorder_suminds,Tuple{Array{δ,1}}}})
    Base.precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(QuantumAlgebra.indices),Tuple{Array{QuantumAlgebra.Corr,1}}}})
    Base.precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(QuantumAlgebra.indices),Tuple{Array{QuantumAlgebra.ExpVal,1}}}})
    Base.precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(corr),Tuple{Array{OpSum,1}}}})
    Base.precompile(Tuple{typeof(Base.Broadcast.preprocess),Array{BaseOperator,1},SubArray{BaseOperator,1,Array{BaseOperator,1},Tuple{StepRange{Int,Int}},true}})
    Base.precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Tuple{OpTerm,Number},1},Array{Tuple{OpTerm,Rational{Int}},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Tuple{OpTerm,Complex{Int}},Int,Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Tuple{OpTerm,Real},1},Array{Tuple{OpTerm,Int},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Tuple{OpTerm,Rational{Int}},Int,Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Tuple{OpTerm,Real},1},Array{Tuple{OpTerm,Rational{Int}},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Tuple{OpTerm,Int},Int,Base.OneTo{Int},Int,Int})
    Base.precompile(Tuple{typeof(Base.Iterators.flatten),Tuple{Array{δ,1},Array{δ,1}}})
    Base.precompile(Tuple{typeof(Base.Order.lt),Base.Order.ForwardOrdering,Tuple{OpTerm,Complex{Int}},Tuple{OpTerm,Complex{Int}}})
    Base.precompile(Tuple{typeof(Base.Order.lt),Base.Order.ForwardOrdering,Tuple{OpTerm,Complex{Int}},Tuple{OpTerm,Rational{Int}}})
    Base.precompile(Tuple{typeof(Base.Order.lt),Base.Order.ForwardOrdering,Tuple{OpTerm,Int},Tuple{OpTerm,Rational{Int}}})
    Base.precompile(Tuple{typeof(Base.Order.lt),Base.Order.ForwardOrdering,Tuple{OpTerm,Rational{Int}},Tuple{OpTerm,Int}})
    Base.precompile(Tuple{typeof(Base.Order.lt),Base.Order.ForwardOrdering,Tuple{OpTerm,Rational{Int}},Tuple{OpTerm,Rational{Int}}})
    Base.precompile(Tuple{typeof(Base.__cat),Array{BaseOperator,1},Tuple{Int},Tuple{Bool},Array{BaseOperator,1},Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(Base.__cat),Array{QuantumAlgebra.Corr,1},Tuple{Int},Tuple{Bool},Array{QuantumAlgebra.Corr,1},Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(Base.__cat),Array{QuantumAlgebra.ExpVal,1},Tuple{Int},Tuple{Bool},Array{QuantumAlgebra.ExpVal,1},Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(Base._collect),UnitRange{Int},Base.Iterators.Flatten{Tuple{Array{BaseOperator,1},Array{BaseOperator,1}}},Base.HasEltype,Base.SizeUnknown})
    Base.precompile(Tuple{typeof(Base._collect),UnitRange{Int},Base.Iterators.Flatten{Tuple{Array{Param,1},Array{Param,1}}},Base.HasEltype,Base.SizeUnknown})
    Base.precompile(Tuple{typeof(Base._collect),UnitRange{Int},Base.Iterators.Flatten{Tuple{Array{QuantumAlgebra.Corr,1},Array{QuantumAlgebra.Corr,1}}},Base.HasEltype,Base.SizeUnknown})
    Base.precompile(Tuple{typeof(Base._collect),UnitRange{Int},Base.Iterators.Flatten{Tuple{Array{QuantumAlgebra.ExpVal,1},Array{QuantumAlgebra.ExpVal,1}}},Base.HasEltype,Base.SizeUnknown})
    Base.precompile(Tuple{typeof(Base.copyto!),Array{OpIndex,1},Int,Array{OpIndex,1},Int,Int})
    Base.precompile(Tuple{typeof(Base.copyto!),Array{δ,1},Int,Array{δ,1},Int,Int})
    Base.precompile(Tuple{typeof(Base.copyto!),Array{BaseOperator,1},Int,Array{BaseOperator,1},Int,Int})
    Base.precompile(Tuple{typeof(Base._front),OpSum,OpSum,Vararg{OpSum,N} where N})
    Base.precompile(Tuple{typeof(Base._typed_vcat),Type{Any},Tuple{Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Array{OpIndex,1}}})
    Base.precompile(Tuple{typeof(Base.afoldl),typeof(*),OpSum,OpSum,OpSum,OpSum,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(Base.afoldl),typeof(*),OpSum,OpSum,OpSum,OpSum,OpSum})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{BaseOperator}})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{OpIndex}})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{OpTerm}})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{QuantumAlgebra.Corr}})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{QuantumAlgebra.ExpVal}})
    Base.precompile(Tuple{typeof(Base.allocatedinline),Type{δ}})
    Base.precompile(Tuple{typeof(Base.cat_indices),Array{BaseOperator,1},Int})
    Base.precompile(Tuple{typeof(Base.cat_indices),Array{QuantumAlgebra.Corr,1},Int})
    Base.precompile(Tuple{typeof(Base.cat_indices),BaseOperator,Int})
    Base.precompile(Tuple{typeof(Base.cat_indices),QuantumAlgebra.Corr,Int})
    Base.precompile(Tuple{typeof(Base.cat_size),Array{BaseOperator,1},Int})
    Base.precompile(Tuple{typeof(Base.cat_size),Array{QuantumAlgebra.Corr,1},Int})
    Base.precompile(Tuple{typeof(Base.cat_size),BaseOperator,Int})
    Base.precompile(Tuple{typeof(Base.cat_size),QuantumAlgebra.Corr,Int})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Array{OpIndex,1},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Array{Param,1},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Array{QuantumAlgebra.Corr,1},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Array{QuantumAlgebra.ExpVal,1},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Array{δ,1},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.deepcopy_internal),Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},IdDict{Any,Any}})
    Base.precompile(Tuple{typeof(Base.ht_keyindex),Dict{OpIndex,OpIndex},OpIndex})
    Base.precompile(Tuple{typeof(Base.ht_keyindex),Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},OpTerm})
    Base.precompile(Tuple{typeof(Base.indexed_iterate),Tuple{OpSum,OpSum},Int})
    Base.precompile(Tuple{typeof(Base.indexed_iterate),Tuple{OpTerm,Float64},Int})
    Base.precompile(Tuple{typeof(Base.indexed_iterate),Tuple{OpTerm,Rational{Int}},Int})
    Base.precompile(Tuple{typeof(Base.print_to_string),QuantumAlgebra.NameIndex,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(Base.promote_eltype),Array{Any,1},Array{OpIndex,1}})
    Base.precompile(Tuple{typeof(Base.vect),OpSum,Vararg{OpSum,N} where N})
    Base.precompile(Tuple{typeof(Core.Compiler.eltype),Type{Array{OpIndex,1}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_corrs!),OpSum,OpTerm,Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Float64},Complex{Float64}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Float64},Float64})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Int},Complex{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Int},Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Int},Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Complex{Rational{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Complex{Rational{Int}},Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Float64,Float64})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Int,Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Int,Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Rational{Int},Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_sum_term!),OpSum,OpTerm,Rational{Int},Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_with_normal_order!),OpSum,OpTerm,Complex{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_with_normal_order!),OpSum,OpTerm,Complex{Rational{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_with_normal_order!),OpSum,OpTerm,Float64})
    Base.precompile(Tuple{typeof(QuantumAlgebra._add_with_normal_order!),OpSum,OpTerm,Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._vacExpVal),OpTerm,Complex{Rational{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra._vacExpVal),OpTerm,Float64})
    Base.precompile(Tuple{typeof(QuantumAlgebra._vacExpVal),OpTerm,Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra._vacExpVal),OpTerm,Rational{Int}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.make_indices),Int,Int,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(QuantumAlgebra.make_indices),Int,Symbol})
    Base.precompile(Tuple{typeof(QuantumAlgebra.make_indices),Symbol,Int})
    Base.precompile(Tuple{typeof(QuantumAlgebra.make_indices),Symbol,Symbol,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(QuantumAlgebra.parse_paramstr),String})
    Base.precompile(Tuple{typeof(QuantumAlgebra.print_term_scalar),Base.GenericIOBuffer{Array{UInt8,1}},OpTerm,Complex{Int},Bool})
    Base.precompile(Tuple{typeof(QuantumAlgebra.print_term_scalar),Base.GenericIOBuffer{Array{UInt8,1}},OpTerm,Int,Bool})
    Base.precompile(Tuple{typeof(QuantumAlgebra.print_term_scalar),Base.GenericIOBuffer{Array{UInt8,1}},OpTerm,Rational{Int},Bool})
    Base.precompile(Tuple{typeof(QuantumAlgebra.simplify_number),Float64})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{4,Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{4,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{5,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{6,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{7,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{8,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,NTuple{9,Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{4,Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{5,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{6,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{7,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{8,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{NTuple{9,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int,Int},Tuple{Int,Int,Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int,Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{4,Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{5,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{6,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{7,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},NTuple{8,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int,Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},NTuple{5,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},NTuple{6,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},NTuple{7,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int,Int,Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},NTuple{5,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},NTuple{6,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int,Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},NTuple{5,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},NTuple{4,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int},Tuple{Int,Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int},Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int},Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.term2corr),OpTerm,Tuple{Tuple{Int}}})
    Base.precompile(Tuple{typeof(QuantumAlgebra.σ),QuantumAlgebra.SpatialIndex,Symbol,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(QuantumAlgebra.σminus),Symbol,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(QuantumAlgebra.σplus),Symbol,Vararg{Symbol,N} where N})
    Base.precompile(Tuple{typeof(adjoint),OpSum})
    Base.precompile(Tuple{typeof(expval_as_corrs),OpSum})
    Base.precompile(Tuple{typeof(cmp),Array{OpIndex,1},Array{OpIndex,1}})
    Base.precompile(Tuple{typeof(cmp),QuantumAlgebra.NameIndex,QuantumAlgebra.NameIndex})
    Base.precompile(Tuple{typeof(collect),Base.Generator{Tuple{Int,Int,Symbol},Type{OpIndex}}})
    Base.precompile(Tuple{typeof(collect),Base.Generator{Tuple{Int},Type{OpIndex}}})
    Base.precompile(Tuple{typeof(collect),Base.Generator{Tuple{Symbol,Symbol,Int},Type{OpIndex}}})
    Base.precompile(Tuple{typeof(collect),Base.Generator{Tuple{Symbol,Symbol,Symbol},Type{OpIndex}}})
    Base.precompile(Tuple{typeof(collect),Base.Generator{Tuple{Symbol},Type{OpIndex}}})
    Base.precompile(Tuple{typeof(comm),OpSum,OpSum})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.reorder_suminds,Tuple{Array{BaseOperator,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.reorder_suminds,Tuple{Array{Param,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.reorder_suminds,Tuple{Array{QuantumAlgebra.Corr,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.reorder_suminds,Tuple{Array{QuantumAlgebra.ExpVal,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.replace_inds,Tuple{Array{BaseOperator,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.replace_inds,Tuple{Array{Param,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.replace_inds,Tuple{Array{QuantumAlgebra.Corr,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.replace_inds,Tuple{Array{QuantumAlgebra.ExpVal,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.shift_sumind,Tuple{Array{BaseOperator,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.shift_sumind,Tuple{Array{Param,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.shift_sumind,Tuple{Array{QuantumAlgebra.Corr,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},QuantumAlgebra.shift_sumind,Tuple{Array{QuantumAlgebra.ExpVal,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},typeof(latex),Tuple{Array{QuantumAlgebra.Corr,1}}}})
    Base.precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},typeof(latex),Tuple{Array{QuantumAlgebra.ExpVal,1}}}})
    Base.precompile(Tuple{typeof(copyto!),Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}}})
    Base.precompile(Tuple{typeof(copyto!),Array{Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int, OpTerm},1},Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}}})
    Base.precompile(Tuple{typeof(eltype),NTuple{9,OpSum}})
    Base.precompile(Tuple{typeof(enumerate),Array{Tuple{OpTerm,Float64},1}})
    Base.precompile(Tuple{typeof(enumerate),Array{Tuple{OpTerm,Int},1}})
    Base.precompile(Tuple{typeof(enumerate),Array{Tuple{OpTerm,Number},1}})
    Base.precompile(Tuple{typeof(enumerate),Array{Tuple{OpTerm,Real},1}})
    Base.precompile(Tuple{typeof(fill!),SubArray{BaseOperator,1,Array{BaseOperator,1},Tuple{UnitRange{Int}},true},BaseOperator})
    Base.precompile(Tuple{typeof(fill!),SubArray{QuantumAlgebra.Corr,1,Array{QuantumAlgebra.Corr,1},Tuple{UnitRange{Int}},true},QuantumAlgebra.Corr})
    Base.precompile(Tuple{typeof(hash),Array{BaseOperator,1},UInt})
    Base.precompile(Tuple{typeof(hash),Array{OpIndex,1},UInt})
    Base.precompile(Tuple{typeof(hash),Array{QuantumAlgebra.Corr,1},UInt})
    Base.precompile(Tuple{typeof(hash),Array{QuantumAlgebra.ExpVal,1},UInt})
    Base.precompile(Tuple{typeof(hash),Array{δ,1},UInt})
    Base.precompile(Tuple{typeof(isempty),OpTerm})
    Base.precompile(Tuple{typeof(iterate),Array{OpSum,1}})
    Base.precompile(Tuple{typeof(iterate),Array{Tuple{OpSum,OpSum},1}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Float64},1}},Tuple{Int,Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Float64},1}},Tuple{Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Int},1}},Tuple{Int,Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Int},1}},Tuple{Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Number},1}},Tuple{Int,Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Number},1}},Tuple{Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Real},1}},Tuple{Int,Int}})
    Base.precompile(Tuple{typeof(iterate),Base.Iterators.Enumerate{Array{Tuple{OpTerm,Real},1}},Tuple{Int}})
    Base.precompile(Tuple{typeof(normal_form),OpSum})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Array{Any,1}})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Array{Int,1}})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Array{Symbol,1}})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Int})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Symbol,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(param),Symbol,Char,Tuple{}})
    Base.precompile(Tuple{typeof(param),Symbol,Char})
    Base.precompile(Tuple{typeof(print),Base.GenericIOBuffer{Array{UInt8,1}},BaseOperator})
    Base.precompile(Tuple{typeof(print),Base.GenericIOBuffer{Array{UInt8,1}},QuantumAlgebra.SpatialIndex})
    Base.precompile(Tuple{typeof(prod),NTuple{4,OpSum}})
    Base.precompile(Tuple{typeof(prod),NTuple{5,OpSum}})
    Base.precompile(Tuple{typeof(prod),NTuple{6,OpSum}})
    Base.precompile(Tuple{typeof(prod),NTuple{7,OpSum}})
    Base.precompile(Tuple{typeof(prod),NTuple{8,OpSum}})
    Base.precompile(Tuple{typeof(prod),NTuple{9,OpSum}})
    Base.precompile(Tuple{typeof(prod),Tuple{OpSum,OpSum,OpSum}})
    Base.precompile(Tuple{typeof(prod),Tuple{OpSum,OpSum}})
    Base.precompile(Tuple{typeof(prod),Tuple{OpSum}})
    Base.precompile(Tuple{typeof(setindex!),Array{BaseOperator,1},Array{BaseOperator,1},UnitRange{Int}})
    Base.precompile(Tuple{typeof(setindex!),Array{QuantumAlgebra.Corr,1},Array{QuantumAlgebra.Corr,1},UnitRange{Int}})
    Base.precompile(Tuple{typeof(setindex!),Array{Tuple{OpTerm,Float64},1},Tuple{OpTerm,Float64},Int})
    Base.precompile(Tuple{typeof(setindex!),Array{Tuple{OpTerm,Int},1},Tuple{OpTerm,Int},Int})
    Base.precompile(Tuple{typeof(setindex!),Array{Tuple{OpTerm,Rational{Int}},1},Tuple{OpTerm,Rational{Int}},Int})
    Base.precompile(Tuple{typeof(setindex!),Array{Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int, OpTerm},1},OpTerm,Int})
    Base.precompile(Tuple{typeof(setindex!),Dict{OpIndex,OpIndex},OpIndex,OpIndex})
    Base.precompile(Tuple{typeof(setindex!),Dict{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},Complex{Rational{Int}},OpTerm})
    Base.precompile(Tuple{typeof(similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Type{Tuple{OpTerm,Float64}}})
    Base.precompile(Tuple{typeof(similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Type{Tuple{OpTerm,Int}}})
    Base.precompile(Tuple{typeof(similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},Type{Tuple},Tuple{Base.Broadcast.Extruded{Array{Pair{OpTerm,Union{Complex{Rational{Int}}, Complex{Float64}, Complex{Int}, Rational{Int}, Float64, Int}},1},Tuple{Bool},Tuple{Int}}}},Type{Tuple{OpTerm,Rational{Int}}}})
    Base.precompile(Tuple{typeof(similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int}},typeof(QuantumAlgebra.indices),Tuple{Base.Broadcast.Extruded{Array{OpTerm,1},Tuple{Bool},Tuple{Int}}}},Type{Array{Any,1}}})
    Base.precompile(Tuple{typeof(sort!),Array{Param,1},Int,Int,Base.Sort.MergeSortAlg,Base.Order.ForwardOrdering,Array{Param,1}})
    Base.precompile(Tuple{typeof(sort!),Array{QuantumAlgebra.Corr,1},Int,Int,Base.Sort.MergeSortAlg,Base.Order.ForwardOrdering,Array{QuantumAlgebra.Corr,1}})
    Base.precompile(Tuple{typeof(sort!),Array{QuantumAlgebra.ExpVal,1},Int,Int,Base.Sort.MergeSortAlg,Base.Order.ForwardOrdering,Array{QuantumAlgebra.ExpVal,1}})
    Base.precompile(Tuple{typeof(sort!),Array{Tuple{OpTerm,Float64},1}})
    Base.precompile(Tuple{typeof(sort!),Array{Tuple{OpTerm,Int},1}})
    Base.precompile(Tuple{typeof(sort!),Array{Tuple{OpTerm,Number},1}})
    Base.precompile(Tuple{typeof(sort!),Array{Tuple{OpTerm,Real},1}})
    Base.precompile(Tuple{typeof(sort!),Array{δ,1},Int,Int,Base.Sort.MergeSortAlg,Base.Order.ForwardOrdering,Array{δ,1}})
    Base.precompile(Tuple{typeof(string),QuantumAlgebra.NameIndex,String,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(string),String,OpIndex,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(string),String,QuantumAlgebra.SpatialIndex,Vararg{Any,N} where N})
    Base.precompile(Tuple{typeof(vacA),OpSum})
    Base.precompile(Tuple{typeof(vacA),OpTerm,Complex{Rational{Int}}})
    Base.precompile(Tuple{typeof(vacA),OpTerm,Float64})
    Base.precompile(Tuple{typeof(vacA),OpTerm,Int})
    Base.precompile(Tuple{typeof(vacA),OpTerm,Rational{Int}})
    Base.precompile(Tuple{typeof(vacExpVal),OpSum,OpSum})
    Base.precompile(Tuple{typeof(vcat),Array{BaseOperator,1},Array{BaseOperator,1}})
    Base.precompile(Tuple{typeof(vcat),Array{OpIndex,1},Array{OpIndex,1},Array{OpIndex,1},Vararg{Array{OpIndex,1},N} where N})
    Base.precompile(Tuple{typeof(vcat),Array{OpIndex,1},Array{OpIndex,1}})
    Base.precompile(Tuple{typeof(vcat),Array{δ,1},Array{δ,1}})
    Base.precompile(Tuple{typeof(∑),Symbol,OpSum})
    isdefined(Base.Broadcast, Symbol("#19#20")) && Base.precompile(Tuple{getfield(Base.Broadcast, Symbol("#19#20")),Int})
    isdefined(QuantumAlgebra, Symbol("#21#22")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#21#22")),Array{δ,1},Vararg{Array{δ,1},N} where N})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5")),Int,Vararg{Any,N} where N})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5")),Int})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5")),String})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5")),Symbol,Vararg{Symbol,N} where N})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5")),Symbol})
    isdefined(QuantumAlgebra, Symbol("#ann#5")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#5"))})
    isdefined(QuantumAlgebra, Symbol("#ann#7")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#7")),Int})
    isdefined(QuantumAlgebra, Symbol("#ann#7")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#7")),Symbol})
    isdefined(QuantumAlgebra, Symbol("#ann#7")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#ann#7"))})
    isdefined(QuantumAlgebra, Symbol("#cre#6")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#6")),Int,Vararg{Any,N} where N})
    isdefined(QuantumAlgebra, Symbol("#cre#6")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#6")),Int})
    isdefined(QuantumAlgebra, Symbol("#cre#6")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#6")),Symbol,Vararg{Symbol,N} where N})
    isdefined(QuantumAlgebra, Symbol("#cre#6")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#6")),Symbol})
    isdefined(QuantumAlgebra, Symbol("#cre#6")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#6"))})
    isdefined(QuantumAlgebra, Symbol("#cre#8")) && Base.precompile(Tuple{getfield(QuantumAlgebra, Symbol("#cre#8"))})
end
